<?php
$catname = $this->category['category_name'];
$caticon = $this->category['category_icon'];
?>
<div class="search-result" id="all-results">
      <div class="venue-results">
        <h2 class="heading-2">Search results for “<?php echo $catname; ?>”</h2>
        <div class="row">
          <div class="col-md-8 border-right">
		  <h5>events</h5>
            <div id="upcoming-events" class="row">
               <?php
               foreach($this->events as $event){
               ?>
              <div class="col-md-6 col-sm-6 <?php echo $event['eventid']; ?>">
                <div class="img-wrapper"> <img alt="" src="<?php echo $this->basePath(); ?>/uploads/event/<?php echo $event['img']; ?>">
                  <div class="overlay">
                    <div class="overlay-contents">
                      <h4><?php echo $event['title']; ?><span><?php echo $event['artist']; ?></span></h4>
                      <p class="post-by text-blue"><span class="pull-right"><img src="<?php echo $this->basePath(); ?>/uploads/category/<?php echo $caticon; ?>" width=22 height=25></span>April 16, 2015  •  09:00 PM </p>
                    </div>
                  </div>
                  <!--/overlay--> 
					<div class="hover-overlay">
          <div class="hover-content"><img src="<?php echo $this->basePath('/assets/frontend/images/img-hover-logo.png');?>" alt=""><br>
            <a class="hover_buy" href="<?php echo $this->url('eventdetail', array('eventId' => $event->getId())); ?>">Buy Tickets</a> </div>
        </div>
        <!--/hover-overlay--> 
                  
                </div>
              </div>
                <?php
               }
                ?>
            </div>
            <!--upcoming-events--> 
            
          </div>
          <div class="col-md-4 sidebar-2">
			<h5>artists</h5>
			<ul>
				<li><a href="#">Irish Dart Masters</a></li>
				<li><a href="#">Irish People</a></li>
			</ul>
			
			<h5>venues</h5>
			<ul>
				<li><a href="#">The Irish Village</a></li>				
			</ul>
		  </div>
        </div>
      </div>
      <!--venue-results--> 
    </div>
