<div class="container main">
 
 <div class="checkout-expired">
	<div class="display-middle">
				<div class="block m-bot-40"><img src="images/icon-clock.png" alt="" /></div>
			Transaction Cancelled By User. <br>
You will have <br>
to <span class="bold">repeat the <span class="text-blue"><a href="<?php echo $this->url('eventdetail',array('eventId'=>$eventId)); ?>">checkout process</a></span></span>
	
	</div>
		
 </div><!--checkout expired-->
  
</div>

<!--/main-->